### PR TITLE
Link allperlbooks.com

### PR DESCRIPTION
**Pull request by ash**
Hi, I'd like to add this reference site.

### CODE REVIEW

**Comment by rspier** [comment]
allperlbooks is neat (although pages are slow to load), but I don't think it will actually connect users with the books they might be looking for.  It doesn't answer questions like "What's this book about?  Is it good?  Do other people like it?"

www.perl.org doesn't try to link to every possible interesting perl website.

**Comment by ash** [comment]
Sure, three mod_perl books and one on Mason is much better to recommend in 2015! :-)

**Comment by rspier** [comment]
Are you talking about the Online Library page?  Those are books where a significant amount (usually all) of the content is available for free.

**Comment by ranguard** [comment]
He does have a point though, I don't think mod_perl is really worth pointing people at these days, it has it's place, but it shouldn't seem like it's the best place to start (Frameworks / PSGI apps being that), even if the content is free

**Comment by rspier** [comment]
We have lots of content that could use a refresh.  With the books, we're distributing "what we have".  While mod_perl isn't the current hotness, it's still a sturdy tool and still used by many companies.  (I'm trying to dig up the netcraft statistics on that, but they're not surfacing easily.)

If someone has written a decent free book on PSGI, then we can distribute/link to that too.

**Pull request closed without merging**
