### PR TITLE
Update version to 5.26.2 and use metacpan links

### PR DESCRIPTION
**Pull request by Grinnz**
For https://www.perl.org/get.html http://dev.perl.org/ and http://dev.perl.org/perl5/.

### CODE REVIEW

**Comment by rspier** [comment]
We link to search.cpan.org from these pages.  Thanks for the PR!

**Comment by karenetheridge** [comment]
Why s.c.o rather than metacpan?

**Comment by shadowcat-mst** [comment]
Given at this point metacpan is more actively maintained and search.cpan.org is having intermittent stability issues, it would be nice to change the links to point to the community recommended solution.

**Comment by Grinnz** [comment]
Given https://log.perl.org/2018/05/goodbye-search-dot-cpan-dot-org.html this should probably be revisited.

**Pull request closed without merging**
