### PR TITLE
remove implied profanity, change email

### PR DESCRIPTION
**Pull request by MartinMcGrath**
Hi,

Thanks for your continued efforts supporting Perl. This short PR removes implied profanity and changes the email address listed in the mailto links for the one listed on http://noc.perl.org

Thanks again

### CODE REVIEW

**Comment by ranguard** [comment]
@abh you ok with the change of email address here? - seems sensible to me though?

@MartinMcGrath thanks

**Comment by rspier** [comment]
@MartinMcGrath What's the motivation for this change?  Zero people have complained about the implied profanity since at least 2003.  It's comic-book level implied.  https://www.google.com/search?q=comic+book+cursing&tbm=isch  You find @#$@ in daily newspapers.

Regarding the email, I think we don't want to change it that way.  We generally say "Webmaster at perl.org", for the tiny level of scraping protection it gives us.

**Comment by abh** [comment]
Thanks. :-)

**Comment by MartinMcGrath** [comment]
@rspier I was doing a demonstration of perl, some tools written in perl and the perl eco-system and managed to arrive at this error (by an error of mine, rather than the site). It was a mixed audience and someone pointed this out to me. Personally I'd never even noticed this, however since it makes no functional difference I thought a pr to replace it with something more tame, while maintaining a somewhat playful response.

**Comment by ranguard** [comment]
I really appreciate @MartinMcGrath sorting this out  for us, nothing wrong with us having a professional rather than comic-book level of appearance.

**Comment by rspier** [comment]
I'm happy to see improvements to this page, but how about something more fun and interesting?  A fail camel?  A camel holding a map?  A camel with a helmet and tool kit doing repeirs?

And please follow the convention of most of the rest of the site(s) and use the slightly obfuscated (updated) address.

**Comment by MartinMcGrath** [comment]
If you require a graphic, sorry I don't have any skills in that department. I prefer text in these situations to avoid worrying about any accessibility or rendering issues. 

I've removed the mailto tags and used the format you requested: https://github.com/perlorg/perlweb/pull/203

Perhaps it'd be a CONTRIBUTING.txt/md would be handy?

A grep of the tree shows lots of mailto tags in other places, since I've no idea if they are still live, looking into that will be a job for another day I'm afraid.

**Pull request merged**
