### PR TITLE
perl v5.22.0 is released

### PR DESCRIPTION
**Pull request by rjbs**

### CODE REVIEW

**Comment by abh** [comment]
Thanks; pushing out to the site now.

**Comment by rjbs** [comment]
This says it was deployed but http://www.perl.org/ still shows 5.20.2 as the current version at the top right. 😢

**Comment by MartinMcGrath** [comment]
@rjbs a caching issue perhaps? I see v5.22.0 displayed in the top right on a couple of different networks.

**Comment by abh** [comment]
Yeah, caching. I think the CDN is configured to cache for 24 hours which might be a little long.

**Comment by rjbs** [comment]
Cool, thanks, I'll keep that in mind next year. :-)  It wasn't a big deal, but I wanted to make sure that nothing more needed to be done by me or anybody else.

**Pull request merged**
