### PR TITLE
Link to perldoc to render most current versions of perlfaqs

### PR DESCRIPTION
**Pull request by Grinnz**
Currently perlfaq is released to CPAN, pulled into core, and in addition seems to be duplicated on learn.perl.org. It seems like an unnecessary duplication that leads to more delay in making the latest perlfaqs visible to everyone. Metacpan is going to have the most up to date versions, since even if perldoc.perl.org was showing the latest stable release it would still be behind until the next stable release occurs. So this is a suggestion to just change all links to to the FAQ to link directly to the versions on metacpan. I also changed one link to `/faq` to such, because it was just a page linking to itself which didn't make much sense.

### CODE REVIEW

**Comment by rspier** [comment]
I understand the motivation for this, and I _almost_ just merged it.  

I have two concerns:

1. metacpan can be slow: https://metacpan.org/pod/distribution/perlfaq/lib/perlfaq6.pod just took almost 3.59 to return.  This is frustrating when browsing docs.
2. the rendering of the FAQ is much less friendly on metacpan.  The font is small, things are densely packed together, no max-width makes wrapping weird.

Maybe those don't matter?

The FAQ on learn.perl.org is currently 2 years out of date.  I've just run the script to update it.  So now it's not out of date.  (As soon as the gears turn and caches clear.)

It wouldn't be too hard to automate the updating.

**Comment by Grinnz** [comment]
It's up to you. The metacpan style looks fine to me (though I also disagree with the max width wrapping). It just seems like a lot of infrastructure/setup for something that is already viewable online and automatically up to date. Linking to perldoc.perl.org's version would be sufficient (barring that site's issues) and also avoid the duplication.

**Comment by rspier** [comment]
Let's try perldoc.perl.org then.

Please also update the .htredirects file and delete the "local" copies of the faq.

**Comment by Grinnz** [comment]
Sorry for the delay. Rebased and changed to perldoc links and deleted the local copies. I'm not sure if anything in .htredirects needs updating because it's only pointing to the "beginner" pages which aren't part of core perldocs.

**Comment by Grinnz** [comment]
Ah, I updated .htredirects to have a redirect for existing links to perldoc.

**Comment by rspier** [comment]
Thanks!  Merged!

**Pull request merged**
