### PR TITLE
Remove dead files

### PR DESCRIPTION
**Pull request by steve-m-hay**
Neither of these filenames are legal on Windows, and cause reports of
deleted files as a result of them failing to check out.
I believe both files have been replaced by files with valid filenames
anyway, though:

YAPC::EU::2004.html is virtually identical to yapceu2004venue.html
YAPC::NA::2004.html is virtually identical to yapcna2004cfv.html

### CODE REVIEW

**Comment by abh** [comment]
There is a way to add redirects in some ".foo" file in docs/foundation -- can you do that?  (The www site has a bunch in its file for examples).

**Comment by rspier** [comment]
Actually, the entire docs/foundation/ directory should be deleted.  They no longer host their website on the perlweb infrastructure.

**Comment by abh** [comment]
Oh, that's right. Let's do that then. :-)

**Comment by rspier** [comment]
I've deleted the directory.  Thanks for raising the awareness of this, Steve!

**Pull request closed without merging**
