### PR TITLE
summarize the p5p SOC for the web

### PR DESCRIPTION
**Pull request by rjbs**
I'd like to get this on the web in an easy-to-link-to location so we can link to it from the p5p welcome message.

### CODE REVIEW

**Comment by rjbs** [comment]
Leading whitespace removed.

**Comment by rspier** [comment]
I don't see the new revision.

**Comment by rjbs** [comment]
It's 171658a6dd8d235cf90e2affd81d62a0361f4889

**Comment by rjbs** [comment]
I see.  I had removed OTHER leading whitespace.

I have pushed a new commit, 5715c0e.

I will not be making further commits to this project.

**Pull request closed without merging**
