### PR TITLE
bump for 5.32.0

### PR DESCRIPTION
**Pull request by xsawyerx**

### CODE REVIEW

**Comment by rspier** [comment]
Please sync your client and rebase.  This branch has conflicts that must be resolved.

**Comment by karenetheridge** [comment]
FWIW, github has an option to rebase and squash pull requests when merging, which works great for single-commit PRs (where squashing is a no-op). Click on the right side of the merge button and the option will be in the menu.

**Comment by rspier** [comment]
@karenetheridge I know how to use GitHub, thank you very much.  This commit has conflicts and cannot be auto-merged or auto-rebased.

**Comment by xsawyerx** [comment]
Missed the comment. Fixed. Thanks!

**Pull request merged**
